name: marker
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11

  - poetry=1.8.4

  - conda-forge::pytorch==2.13.0
  - conda-forge::pytorch-gpu==2.13.0

  - pip:
    - -e ./marker[full]
    # for streamlit
    - streamlit==1.59.2
    - streamlit-ace==0.1.1
    # for gradio
    - gradio[mcp]==5.28.0
    # for run_ocr_errors feat
    # override old version for conflict
    # - pdftext==0.7.1
