name: marker
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11

  - poetry=1.8.4

  - conda-forge::pytorch==2.7.0
  - conda-forge::pytorch-gpu==2.7.0

  - streamlit==1.41.1

  - pip:
    - -e ./marker[full]
    - streamlit-ace==0.1.1
    - gradio[mcp]==5.28.0
    # gradio[mcp] 5.28.0 depends on pydantic>=2.11
    - pydantic==2.11.4
    # mcp 1.9.1 still exists bug see this https://github.com/modelcontextprotocol/python-sdk/issues/101
    - mcp==1.7.1
