name: marker
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11

  - poetry=1.8.4

  - pytorch==2.5.1
  - pytorch-cuda==12.4

  - streamlit==1.41.1

  - pip:
    - -e ./marker
    - gradio[mcp]==5.28.0
    # gradio[mcp] 5.28.0 depends on pydantic>=2.11
    - pydantic==2.11.4
    - transformers==4.47.1
    # mcp 1.9.1 still exists bug see this https://github.com/modelcontextprotocol/python-sdk/issues/101
    - mcp==1.7.1
