

services:
  marker_gradio:
    image: xiaoyao9184/marker:1.8.3
    container_name: marker_pdf_gradio
    working_dir: /workspace/gradio
    command: gradio gradio_app.py
    environment:
      - TORCH_DEVICE=cpu
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - RECOGNITION_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_recognition/2025_05_16
      - LAYOUT_MODEL_CHECKPOINT=/root/.cache/datalab/models/layout/2025_02_18
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - TABLE_REC_MODEL_CHECKPOINT=/root/.cache/datalab/models/table_recognition/2025_02_18
    ports:
      - "7860:7860"
    volumes:
      - ./../../cache:/root/.cache
