
FROM alpine/curl:latest AS fonts

WORKDIR /fonts

RUN curl -L -o /fonts/GoNotoCurrent-Regular.ttf https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoCurrent-Regular.ttf \
    && curl -L -o /fonts/GoNotoCJKCore.ttf https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoCJKCore.ttf


FROM pytorch/pytorch:2.13.0-cuda12.6-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./marker /app
# The image is too large, with layers exceeding 10GB.
# RUN pip3 install poetry
# RUN poetry install --no-root --with dev
RUN pip3 install --no-cache-dir \
    -e .

# Lock streamlit version
RUN pip3 install --no-cache-dir \
    streamlit==1.59.2 \
    streamlit-ace==0.1.1

# Lock gradio version
RUN pip3 install --no-cache-dir \
    gradio[mcp]==5.28.0

# Override incorrect version
RUN pip3 install --no-cache-dir \
    pypdfium2==4.30.0 \
    pdftext==0.6.3 \
    mcp==1.7.1 \
    pydantic==2.11.4

COPY ./gradio /workspace/gradio

EXPOSE 8501
EXPOSE 7860

VOLUME /root/.cache

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["marker_gui"]
