ARG MARKER_VERSION=1.6.0
ARG STREAMLIT_VERSION=1.41.1
ARG GRADIO_VERSION=5.28.0


FROM alpine/curl:latest AS fonts

WORKDIR /fonts

RUN curl -L -o /fonts/GoNotoCurrent-Regular.ttf https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoCurrent-Regular.ttf \
    && curl -L -o /fonts/GoNotoCJKCore.ttf https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoCJKCore.ttf


FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

ARG MARKER_VERSION
ARG STREAMLIT_VERSION
ARG GRADIO_VERSION

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    marker-pdf[full]==${MARKER_VERSION} \
    streamlit==${STREAMLIT_VERSION} \
    pydantic==2.11.4 \
    transformers==4.47.1 \
    mcp==1.7.1 \
    gradio[mcp]==${GRADIO_VERSION}

# COPY --from=fonts /fonts/GoNotoCurrent-Regular.ttf /fonts/GoNotoCurrent-Regular.ttf
# COPY --from=fonts /fonts/GoNotoCJKCore.ttf /fonts/GoNotoCJKCore.ttf
COPY --from=fonts /fonts/GoNotoCurrent-Regular.ttf /opt/conda/lib/python3.11/site-packages/static/fonts/GoNotoCurrent-Regular.ttf
COPY --from=fonts /fonts/GoNotoCJKCore.ttf /opt/conda/lib/python3.11/site-packages/static/fonts/GoNotoCJKCore.ttf

COPY ./gradio /workspace/gradio

EXPOSE 8501
EXPOSE 7860

VOLUME /root/.cache

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["marker_gui"]
